# Generated by Django 4.2.11 on 2024-04-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='CPU')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'СPU',
                'verbose_name_plural': 'СPU',
                'db_table': 'CpuInfo',
                'ordering': ('date',),
            },
        ),
    ]
